/* Copyright 2003 MakingThings LLC. */

#ifndef _INTROAINDEV_
#define _INTROAINDEV_

/** \file TeleoMioAinDefines.h
    Defines for the MultiIO Ain Device.
 */

//
// DEFINES
//

#define INTROAINDEV_DEVICE_OFFSET       0

#define INTROAINDEV_PROPERTY_VALUE      0
#define INTROAINDEV_PROPERTY_PERIOD     1
#define INTROAINDEV_PROPERTY_RESOLUTION 2

#define INTROAINDEV_DEVICE_DEFAULT      0
#define INTROAINDEV_DEVICE_MIN          0
#define INTROAINDEV_DEVICE_MAX          3

#define INTROAINDEV_PERIOD_DEFAULT      100
#define INTROAINDEV_PERIOD_MIN          0
#define INTROAINDEV_PERIOD_MAX          1000

#define INTROAINDEV_RESOLUTION_DEFAULT  5
#define INTROAINDEV_RESOLUTION_MIN      1
#define INTROAINDEV_RESOLUTION_MAX      10

#endif
