/* Copyright 2003 MakingThings LLC. */

#ifndef _TELEOMOTORDEFINES_H_
#define _TELEOMOTORDEFINES_H_

/** \file TeleoMotorDefines.h
    Defines for the Teleo Motor Device.
 */

/*
: set ts=2 sw=2
*/

//
// DEFINES
//
#define MOTORDEV_PORT_SPEED          			 0
#define MOTORDEV_PORT_SPEED_MAX      			 1
#define MOTORDEV_PORT_BRAKE_ON       			 2
#define MOTORDEV_PORT_ON             			 3
#define MOTORDEV_PORT_INVERT         			 4
#define MOTORDEV_PORT_CUR_SAMPLE_RATE 		 5
#define MOTORDEV_PORT_CURRENT        			 6
#define MOTORDEV_PORT_CURRENT_MAX    			 7
#define MOTORDEV_PORT_LIMITA         			 8
#define MOTORDEV_PORT_LIMITB         			 9
#define MOTORDEV_PORT_LIMITS_ON     		  10
#define MOTORDEV_PORT_POSITION            11
#define MOTORDEV_PORT_POSITION_MIN        12
#define MOTORDEV_PORT_POSITION_MAX        13
#define MOTORDEV_PORT_POS_SAMPLE_RATE     14
#define MOTORDEV_PORT_POSITION_RESOLUTION 15


#define MOTORDEV_DEFAULT_SPEED      	    0
#define MOTORDEV_DEFAULT_SPEED_MAX        100
#define MOTORDEV_DEFAULT_BRAKE_ON           0
#define MOTORDEV_DEFAULT_ON                 1
#define MOTORDEV_DEFAULT_INVERT             0
#define MOTORDEV_DEFAULT_CUR_SAMPLE_RATE  100
#define MOTORDEV_DEFAULT_CURRENT_MAX    30000
#define MOTORDEV_DEFAULT_LIMITS_ON          0
#define MOTORDEV_DEFAULT_POSITION_MIN  -100.0
#define MOTORDEV_DEFAULT_POSITION_MAX   100.0
#define MOTORDEV_DEFAULT_POS_SAMPLE_RATE  100

#define MOTORDEV_MIN_VALID_SPEED      	  -1024
#define MOTORDEV_MIN_VALID_SPEED_MAX          0
#define MOTORDEV_MIN_VALID_BRAKE_ON           0
#define MOTORDEV_MIN_VALID_ON                 0
#define MOTORDEV_MIN_VALID_INVERT             0
#define MOTORDEV_MIN_VALID_CUR_SAMPLE_RATE    0
#define MOTORDEV_MIN_VALID_CURRENT_MAX        0
#define MOTORDEV_MIN_VALID_LIMITS_ON          0
#define MOTORDEV_MIN_VALID_POSITION_MIN   -1024
#define MOTORDEV_MIN_VALID_POSITION_MAX   -1024
#define MOTORDEV_MIN_VALID_POS_SAMPLE_RATE    0

#define MOTORDEV_MAX_VALID_SPEED      	   1024
#define MOTORDEV_MAX_VALID_SPEED_MAX       1024
#define MOTORDEV_MAX_VALID_BRAKE_ON           1
#define MOTORDEV_MAX_VALID_ON                 1
#define MOTORDEV_MAX_VALID_INVERT             1
#define MOTORDEV_MAX_VALID_CUR_SAMPLE_RATE 1000
#define MOTORDEV_MAX_VALID_CURRENT_MAX     2000
#define MOTORDEV_MAX_VALID_LIMITS_ON          1
#define MOTORDEV_MAX_VALID_POSITION_MIN    1024
#define MOTORDEV_MAX_VALID_POSITION_MAX    1024
#define MOTORDEV_MAX_VALID_POS_SAMPLE_RATE 1000

#define MOTORDEV_DEFAULT_VALID_DEVICE         0

#define MOTORDEV_MIN_VALID_RESOLUTION         1
#define MOTORDEV_MAX_VALID_RESOLUTION        10
#define MOTORDEV_DEFAULT_RESOLUTION           5

#endif
