/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import <QuartzComposer/QCInspector.h>

@class NSButton;

@interface QCClearUI : QCInspector
{
    NSButton *colorButton;
    NSButton *depthButton;
}

+ (id)viewNibName;
- (void)setupViewForPatch:(id)fp8;
- (void)update:(id)fp8;

@end

