/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EventSim */

#ifndef _Included_EventSim
#define _Included_EventSim
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EventSim
 * Method:    enableEventStateCombining
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_EventSim_enableEventStateCombining
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     EventSim
 * Method:    postMouseEvent
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_EventSim_postMouseEvent
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     EventSim
 * Method:    postScrollEvent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_EventSim_postScrollEvent
  (JNIEnv *, jclass, jint);

/*
 * Class:     EventSim
 * Method:    postKeyEvent
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_EventSim_postKeyEvent
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
