/*
* ============================================================================
*  Name     : CMPToolkitDocument from MPToolkitDocument.h
*  Part of  : MPToolkit
*  Created  : 01.11.2005 by Faraz Ahmed Memon
*  Implementation notes:
*     Initial content was generated by Series 60 Application Wizard.
*  Version  :
*  Copyright: i10 RWTH Aachen
* ============================================================================
*/

#include "MPToolkitDocument.h"
#include "MPToolkitAppui.h"


CMPToolkitDocument::CMPToolkitDocument(CEikApplication& aApp):CAknDocument(aApp)    
{
}


CMPToolkitDocument::~CMPToolkitDocument()
{
}

void CMPToolkitDocument::ConstructL()
{
}

CMPToolkitDocument* CMPToolkitDocument::NewL(CEikApplication& aApp)
{
    CMPToolkitDocument* self = new (ELeave) CMPToolkitDocument( aApp );
    CleanupStack::PushL( self );
    self->ConstructL();
    CleanupStack::Pop();

    return self;
}
    
CEikAppUi* CMPToolkitDocument::CreateAppUiL()
{
    return new (ELeave) CMPToolkitAppUi;
}