/* ============================================================================
*  Name     : CMPToolkitApp from MPToolkitApp.cpp
*  Part of  : MPToolkit
*  Created  : 01.11.2005 by Faraz Ahmed Memon
* 
*  Implementation notes:
*
*     Initial content was generated by Series 60 Application Wizard.
*  Version  :
*  Copyright: i10 RWTH Aachen
* ============================================================================
*/

#include    "MPToolkitApp.h"
#include    "MPToolkitDocument.h"


TUid CMPToolkitApp::AppDllUid() const
{
    return KUidMPToolkit;
}


CApaDocument* CMPToolkitApp::CreateDocumentL()
{
    return CMPToolkitDocument::NewL( *this );
}


EXPORT_C CApaApplication* NewApplication()
{
    return new CMPToolkitApp;
}


GLDEF_C TInt E32Dll( TDllReason )
{
    return KErrNone;
}